=== Qwertyblob/sghousing/site/src/schemas/lease_decay.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "lease_decay.json",
  "description": "Price per sqm by whole years of remaining lease and flat type ('ALL' rollup).",
  "type": "object",
  "required": [
    "columns",
    "rows",
    "from",
    "to",
    "min_sales"
  ],
  "properties": {
    "columns": {
      "const": [
        "flat_type",
        "lease_years",
        "sales",
        "median_psm",
        "median_rel_psm"
      ]
    },
    "rows": {
      "type": "array",
      "items": {
        "type": "array",
        "prefixItems": [
          {
            "type": "string"
          },
          {
            "type": "integer",
            "minimum": 0,
            "maximum": 99
          },
          {
            "type": "integer"
          },
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "minItems": 5,
        "maxItems": 5
      }
    },
    "from": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}$"
    },
    "to": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}$"
    },
    "min_sales": {
      "type": "integer"
    }
  },
  "additionalProperties": false
}

=== Qwertyblob/sghousing/data/lease_decay.json
{"from":"2021-11","to":"2026-10","min_sales":30,"columns":["flat_type","lease_years","sales","median_psm","median_rel_psm"],"rows":[["2 ROOM",41,36,6353.27,0.9615],["2 ROOM",42,46,6170.21,0.9555],["2 ROOM",43,48,6192.51,0.966],["2 ROOM",44,75,6145.83,0.9746],["2 ROOM",45,38,6082.23,1.0007],["2 ROOM",46,37,6000,0.999],["2 ROOM",47,45,5875,1],["2 ROOM",52,32,6818.18,0.9751],["2 ROOM",53,38,6545.45,0.9979],["2 ROOM",54,40,6250,0.9701],["2 ROOM",59,36,7065.39,1.0078],["2 ROOM",86,67,7848.68,0.9772],["2 ROOM",87,118,7872.34,0.9742],["2 ROOM",88,184,7872.34,0.9845],["2 ROOM",89,188,7446.81,0.968],["2 ROOM",90,170,7182.7,0.9979],["2 ROOM",91,246,7446.81,0.9909],["2 ROOM",92,299,7978.72,1],["2 ROOM",93,422,8042.55,1.0189],["2 ROOM",94,821,7872.34,1.0229],["2 ROOM",95,135,7446.81,1.029],["3 ROOM",39,59,5223.88,0.8149],["3 ROOM",40,104,5588.28,0.9115],["3 ROOM",41,184,5669.4,0.9366],["3 ROOM",42,289,5555.56,0.9286],["3 ROOM",43,433,5535.71,0.9233],["3 ROOM",44,447,5522.39,0.93],["3 ROOM",45,547,5417.91,0.9394],["3 ROOM",46,600,5384.62,0.93],["3 ROOM",47,611,5625,0.9345],["3 ROOM",48,691,5746.27,0.9509],["3 ROOM",49,816,5753.42,0.9475],["3 ROOM",50,990,5820.9,0.9547],["3 ROOM",51,1134,5865.04,0.9701],["3 ROOM",52,1245,5820.9,0.9823],["3 ROOM",53,1367,5792.68,0.9872],["3 ROOM",54,1387,5666.67,0.9835],["3 ROOM",55,1277,5600,0.9872],["3 ROOM",56,1234,5542.33,0.9797],["3 ROOM",57,1390,5769.23,0.9805],["3 ROOM",58,1466,5980.23,0.9932],["3 ROOM",59,1601,5931.51,0.9944],["3 ROOM",60,1547,5753.42,0.9898],["3 ROOM",61,1497,5621.62,0.9922],["3 ROOM",62,1089,5560.75,0.9907],["3 ROOM",63,586,5479.45,0.9807],["3 ROOM",64,424,5212.16,0.9668],["3 ROOM",65,196,5006.85,0.9455],["3 ROOM",66,85,5095.89,0.9538],["3 ROOM",67,45,6171.88,1.016],["3 ROOM",68,47,5932.2,1.0114],["3 ROOM",69,44,5348.55,1.0021],["3 ROOM",81,32,10066.67,1.576],["3 ROOM",82,33,11166.67,1.7331],["3 ROOM",83,50,9860.87,1.7347],["3 ROOM",84,62,9586.96,1.4916],["3 ROOM",85,120,8846.4,1.4642],["3 ROOM",86,210,8148.05,1.2669],["3 ROOM",87,342,8059.7,1.2479],["3 ROOM",88,579,7731.34,1.1574],["3 ROOM",89,678,7611.94,1.1258],["3 ROOM",90,715,7537.31,1.1596],["3 ROOM",91,882,7466.64,1.1628],["3 ROOM",92,935,7470.59,1.1722],["3 ROOM",93,1091,7462.69,1.2112],["3 ROOM",94,1856,7313.43,1.2416],["3 ROOM",95,418,6963.13,1.2338],["4 ROOM",46,56,5902.1,0.6116],["4 ROOM",47,108,6151.64,0.6383],["4 ROOM",48,171,5951.22,0.7226],["4 ROOM",49,236,5975.61,0.7179],["4 ROOM",50,348,5911.86,0.8371],["4 ROOM",51,479,5853.66,0.8385],["4 ROOM",52,490,5741.52,0.8804],["4 ROOM",53,622,5623.6,0.8953],["4 ROOM",54,645,5533.33,0.9104],["4 ROOM",55,551,5362.64,0.8936],["4 ROOM",56,488,5441.52,0.9],["4 ROOM",57,904,5576.92,0.8913],["4 ROOM",58,1227,5761.9,0.9127],["4 ROOM",59,1522,5714.29,0.9253],["4 ROOM",60,1733,5569.89,0.933],["4 ROOM",61,1983,5384.62,0.9377],["4 ROOM",62,1849,5357.14,0.9409],["4 ROOM",63,1324,5224.86,0.9422],["4 ROOM",64,1161,5035.71,0.9407],["4 ROOM",65,1014,4900.04,0.9276],["4 ROOM",66,667,5288.46,0.9483],["4 ROOM",67,535,5432.69,0.9534],["4 ROOM",68,589,5283.02,0.9477],["4 ROOM",69,830,5315.52,0.9432],["4 ROOM",70,1013,5549.45,0.9551],["4 ROOM",71,1232,5600,0.9589],["4 ROOM",72,1396,5519.61,0.9549],["4 ROOM",73,1592,5400,0.9634],["4 ROOM",74,1482,5345.68,0.9558],["4 ROOM",75,1275,5643.56,0.9581],["4 ROOM",76,1189,5647.06,0.9574],["4 ROOM",77,1098,5777.78,0.9668],["4 ROOM",78,899,5777.78,0.9735],["4 ROOM",79,759,6043.48,0.9629],["4 ROOM",80,628,6026.83,0.9616],["4 ROOM",81,503,6888.89,1.0235],["4 ROOM",82,428,8255.44,1.0816],["4 ROOM",83,472,8601.08,1.0822],["4 ROOM",84,413,8369.57,1.1223],["4 ROOM",85,658,7723.69,1.0727],["4 ROOM",86,866,7341.56,1.0707],["4 ROOM",87,1180,7259.47,1.0685],["4 ROOM",88,1682,7043.25,1.0751],["4 ROOM",89,1979,6860.22,1.0736],["4 ROOM",90,1852,6847.83,1.0845],["4 ROOM",91,2293,6881.72,1.101],["4 ROOM",92,2677,6720.43,1.1033],["4 ROOM",93,3226,6839.81,1.1041],["4 ROOM",94,5555,6967.74,1.1258],["4 ROOM",95,1053,6795.7,1.1365],["5 ROOM",47,43,7789.47,0.8526],["5 ROOM",48,81,6837.61,0.8589],["5 ROOM",49,136,6564.1,0.878],["5 ROOM",50,181,6398.31,0.841],["5 ROOM",51,218,6426.23,0.8722],["5 ROOM",52,304,6008.77,0.8631],["5 ROOM",53,300,5775.84,0.8639],["5 ROOM",54,297,5769.23,0.8816],["5 ROOM",55,269,5528,0.8844],["5 ROOM",56,269,5583.33,0.9209],["5 ROOM",57,397,5548.87,0.8949],["5 ROOM",58,460,5590.73,0.9055],["5 ROOM",59,539,5537.19,0.9133],["5 ROOM",60,622,5491.8,0.9201],["5 ROOM",61,721,5409.84,0.9304],["5 ROOM",62,681,5475.41,0.9298],["5 ROOM",63,580,5400.1,0.9422],["5 ROOM",64,507,5204.92,0.9414],["5 ROOM",65,493,5151.52,0.9475],["5 ROOM",66,454,5670.22,0.9603],["5 ROOM",67,364,5725.81,0.9675],["5 ROOM",68,486,5478.84,0.9741],["5 ROOM",69,748,5434.79,0.9788],["5 ROOM",70,946,5414.95,0.9777],["5 ROOM",71,970,5573.77,0.9921],["5 ROOM",72,1245,5450.82,0.9862],["5 ROOM",73,1340,5446.24,0.9937],["5 ROOM",74,1338,5495.87,0.9874],["5 ROOM",75,1407,5472.97,0.9843],["5 ROOM",76,1427,5401.79,0.9688],["5 ROOM",77,1448,5363.64,0.9701],["5 ROOM",78,1191,5272.73,0.9637],["5 ROOM",79,935,5217.16,0.9484],["5 ROOM",80,640,5090.91,0.9331],["5 ROOM",81,351,5272.73,0.9859],["5 ROOM",82,176,5950.45,1.0782],["5 ROOM",83,156,8091.33,1.1304],["5 ROOM",84,145,9776.79,1.2723],["5 ROOM",85,196,9866.67,1.3375],["5 ROOM",86,185,9322.03,1.2714],["5 ROOM",87,267,8620.69,1.2311],["5 ROOM",88,501,7392.86,1.1717],["5 ROOM",89,574,7101.28,1.1652],["5 ROOM",90,684,6858.41,1.1584],["5 ROOM",91,1014,6771.71,1.1502],["5 ROOM",92,1198,6562.5,1.1386],["5 ROOM",93,1230,6506.18,1.1486],["5 ROOM",94,2143,6725.66,1.1876],["5 ROOM",95,341,6371.68,1.1844],["ALL",39,69,5250,0.8149],["ALL",40,124,5743.99,0.9263],["ALL",41,224,5801.79,0.9373],["ALL",42,338,5666.67,0.9313],["ALL",43,495,5590.91,0.9228],["ALL",44,539,5606.06,0.9328],["ALL",45,612,5492.54,0.9368],["ALL",46,702,5473.14,0.9228],["ALL",47,812,5757.58,0.9178],["ALL",48,979,5869.57,0.9295],["ALL",49,1215,5914.63,0.9279],["ALL",50,1549,5897.44,0.9291],["ALL",51,1871,5940.3,0.9432],["ALL",52,2077,5846.15,0.9483],["ALL",53,2334,5746.27,0.953],["ALL",54,2379,5659.34,0.9537],["ALL",55,2136,5552.24,0.9567],["ALL",56,2031,5531.91,0.9565],["ALL",57,2793,5708.33,0.9454],["ALL",58,3360,5868.41,0.9536],["ALL",59,3981,5826.67,0.9604],["ALL",60,4312,5691.75,0.9623],["ALL",61,4709,5561.22,0.9633],["ALL",62,4150,5522.39,0.9636],["ALL",63,2899,5409.84,0.9579],["ALL",64,2392,5191.02,0.9563],["ALL",65,2099,5136.99,0.9518],["ALL",66,1523,5657.41,0.9641],["ALL",67,1291,5737.7,0.9701],["ALL",68,1583,5569.11,0.9674],["ALL",69,2142,5476.84,0.9701],["ALL",70,2501,5500,0.9716],["ALL",71,2693,5625,0.9811],["ALL",72,3100,5520.33,0.9785],["ALL",73,3374,5467.74,0.9856],["ALL",74,3260,5498.3,0.98],["ALL",75,3133,5560.34,0.9827],["ALL",76,2992,5500,0.9715],["ALL",77,2838,5500,0.9754],["ALL",78,2310,5444.44,0.9701],["ALL",79,1821,5500,0.9589],["ALL",80,1330,5454.55,0.9517],["ALL",81,899,5879.12,1.005],["ALL",82,646,7913.04,1.0873],["ALL",83,687,8470.59,1.1066],["ALL",84,631,8602.15,1.1417],["ALL",85,1003,8064.52,1.1111],["ALL",86,1328,7759.91,1.1008],["ALL",87,1907,7627.12,1.1007],["ALL",88,2946,7333.33,1.0986],["ALL",89,3419,7104.48,1.0902],["ALL",90,3421,6989.25,1.1123],["ALL",91,4435,6973.45,1.114],["ALL",92,5109,6869.76,1.1139],["ALL",93,5969,6989.25,1.1161],["ALL",94,10375,7065.22,1.1431],["ALL",95,1947,6838.24,1.1503],["EXECUTIVE",57,87,6453.33,0.9882],["EXECUTIVE",58,182,6233.33,0.9639],["EXECUTIVE",59,280,6208.92,0.9801],["EXECUTIVE",60,382,5986.66,0.9883],["EXECUTIVE",61,480,6013.42,0.9989],["EXECUTIVE",62,515,5973.15,0.9955],["EXECUTIVE",63,399,5774.65,0.9957],["EXECUTIVE",64,289,5719.18,1.0078],["EXECUTIVE",65,393,5924.66,1.0053],["EXECUTIVE",66,317,6164.38,0.9959],["EXECUTIVE",67,344,6086.41,0.9856],["EXECUTIVE",68,460,5882.79,0.9857],["EXECUTIVE",69,520,5713.03,0.9924],["EXECUTIVE",70,522,5536.72,0.995],["EXECUTIVE",71,479,5784.72,1.0088],["EXECUTIVE",72,449,5839.16,1.0095],["EXECUTIVE",73,426,5851.11,1.0324],["EXECUTIVE",74,431,5807.69,1.024],["EXECUTIVE",75,434,5679.42,1.0154],["EXECUTIVE",76,356,5484.41,1.003],["EXECUTIVE",77,271,5230.77,1.0001],["EXECUTIVE",78,205,5040,1],["EXECUTIVE",79,107,5357.14,1.0051],["EXECUTIVE",80,41,5115.38,1.0028]]}
